### ISSUE TITLE
Preciso de ajuda

### ISSUE THREAD

**Issue by iprtl** [thomraider12/canaistvpt#3]
Ola tudo bem. podes me dizer como adicionar (.github/workflows). Estou a tentar incluir outro mas nao consigo. Tem a  ver com youtube. https://github.com/abskmj/iptv-youtube-live/tree/main/.github/workflows

**Comment by thomraider12** [comment]
Boa tarde.
Queres saber como crias a pasta?

**Comment by inspirationlinks** [comment]
sim e nao lol Buscar aos outros e colocar no meu ou fazer eu mesmo um

**Comment by inspirationlinks** [comment]
Sim queria aproveitar e aos mesmo tempo saber como se faz

**Comment by thomraider12** [comment]
Tens algum tipo de serviço de mensagem? Discord por exemplo?

**Comment by inspirationlinks** [comment]
tenho
nome de usuario jerry_64400
e tenho telegram @JerryNilo
Estou mais habituado ao telegram o Discord raramente la vou
